# Generated by Django 3.1.4 on 2021-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('avion_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puestos_Disponibles', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=30)),
                ('correo', models.EmailField(max_length=105)),
                ('celular', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('viaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaViaje', models.DateTimeField()),
                ('fechaLlegada', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
