# Generated by Django 3.1.4 on 2021-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_viaje_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='masculino', max_length=30),
        ),
    ]
