# Generated by Django 3.1.4 on 2021-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20210224_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
